server:
  port: ${port:60901}

#项目名等配置
site:
  app-name: icebartech-enweis
  explanation: 手机膜
  host: enweis.icebartech.com
  session-expires: 7D

spring:
  redis:
    timeout: 30m

# 默认使用开发环境
spring.profiles.active: dev