server.servlet.context-path: /api
jasypt.encryptor.password: tyui2000

spring:
  http.encoding:
    charset: UTF-8
    enabled: true
    force: true
  redis:
    database: 1
    host: 120.76.102.155
    port: 6379
    password: ENC(9MVPGuwIk+iW6h7BKK0Ssb+adoK96EGrXHyhhu+t7ers3Jf+fCd5H5KoaBnX06N+)
    #连接超时时间
    timeout: 5s
    jedis:
      pool:
        #最大连接数
        max-active: 1000
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1ms
        #最大空闲
        max-idle: 10
        #最小空闲
        min-idle: 2
  datasource:
    # druid
    type: com.alibaba.druid.pool.DruidDataSource

  # JPA框架
#  jpa:
#    #open-in-view: true # 多对多关系相互引用中，需要让session在相应过程中保持开启状态，懒加载用到
#    show-sql: false # 不显示sql
#    generate-ddl: true
#    hibernate:
#      ddl-auto: update # 设置变动了则改变表结构
