# 手机膜-开发环境（开发环境）
site:
  app-name: icebartech-enweis-test
  explanation: 手机膜开发环境
  #host: phoneparts.icebartech.com
  host: localhost:60901

spring:
  # 测试环境Redis
  redis:
    database: 0
    host: 120.78.135.29
    port: 6379
    password:

  # 测试环境MySQL
  datasource:
    url: jdbc:mysql://120.78.135.29:3306/phoneparts_v4_bak?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true&useCompression=true&zeroDateTimeBehavior=convertToNull
    username: phoneparts
    password: phoneparts
  jpa:
    show-sql: true # 不显示sql
    generate-ddl: true
    hibernate:
      ddl-auto: update # 设置变动了则改变表结构

  # sms短信
  sms:
    url: https://api.mysubmail.com/message/xsend.json
    appId: 52983
    appKey: cab23130148380dc4adc9ceb72e2b4d8
    mode: prod
    project-codes:
      - p3b9J1 #验证码模板

  # SUBMAIL邮箱
  mail:
    from: phone
    url: https://api.mysubmail.com/mail/xsend.json
    appid: 14561
    appKey: fe8dfa6bf7883c20cbb7f14ab8abe35a
    templates:
      - 1f12C2

# 阿里云OSS
aliyun:
  access-id: LTAIt3vIGEQOyxs7
  access-key: vmlIoysSPo9D14NXheYLpSHdqBAf96
  oss-endpoint: http://oss-cn-hongkong.aliyuncs.com/
  oss-url: https://cut0820.oss-accelerate.aliyuncs.com
  bucket-name: cut0820

