server:
  port: ${port:60901}

# jasypt 加密配置文件，省的阿里云报错：https://blog.csdn.net/dyccsxg/article/details/9672361
jasypt.encryptor.password: tyui2000

#项目名等配置
site:
  app-name: icebartech-enweis
  explanation: 手机膜
  host: enweis.icebartech.com
  session-expires: 7D

spring:
  jpa:
    show-sql: true # 不显示sql
    generate-ddl: true
    hibernate:
      ddl-auto: update # 设置变动了则改变表结构
  redis:
    timeout: 30m
  #SUBMAIL邮箱
  mail:
    from: phone
    url: https://api.mysubmail.com/mail/xsend.json
    appid: 14561
    appKey: fe8dfa6bf7883c20cbb7f14ab8abe35a
    templates:
      - 1f12C2

# 默认使用开发环境
spring.profiles.active: dev