#site:
#  app-name: icebartech-enweis-test
#  explanation: 手机膜开发环境
#  #host: phoneparts.icebartech.com
#  host: localhost:60901
#
#spring:
#  redis:
#    database: 1
#    host: 120.76.102.155
#    port: 6379
#    password: ENC(9MVPGuwIk+iW6h7BKK0Ssb+adoK96EGrXHyhhu+t7ers3Jf+fCd5H5KoaBnX06N+)
#  datasource:
#    url: jdbc:mysql://120.78.135.29:3306/phoneparts_test?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true&useCompression=true&zeroDateTimeBehavior=convertToNull
#    username: phoneparts
#    password: phoneparts
#  jpa:
#    #open-in-view: true # 多对多关系相互引用中，需要让session在相应过程中保持开启状态，懒加载用到
#    show-sql: true # 不显示sql
#    generate-ddl: true
#    hibernate:
#      ddl-auto: update # 设置变动了则改变表结构
#  #sms短信
#  sms:
#    url: https://api.mysubmail.com/message/xsend.json
#    appId: 31370
#    appKey: f3e60c0666da2fe043cbf03e0a030026
#    mode: prod
#    project-codes:
#      - bFI3q2 #验证码模板
#  #SUBMAIL邮箱
#  mail:
#    from: phone
#    url: https://api.mysubmail.com/mail/xsend.json
#    appid: 14561
#    appKey: fe8dfa6bf7883c20cbb7f14ab8abe35a
#    templates:
#      - 1f12C2
#
##aliyun:
##  access-id: ENC(UnP3gTfd/TsB1vJqbfNt9I6rot75wvx9r7Pz6Yefx/w=)
##  access-key: ENC(P8ScPsQwFVW5112JkHoGWhgbfO8Jd1TRxQHbQYpsaJPcVQOv5us6cQ==)
##  oss-endpoint: http://oss-cn-shenzhen.aliyuncs.com/
##  oss-url: https://file.icebartech.com
##  bucket-name: icebar
#
#aliyun:
# access-id: ENC(O+c/lJmhbRC6WuEjS0vX8Df0DIh+K3NNsXH6AekcnSE=)
# access-key: ENC(3rePYhvqlmMB7vSbGJwhNZA4IEI0sOMy7WxLS+aH2y5hOgM+IYDTSA==)
#  oss-endpoint: http://oss-cn-hongkong.aliyuncs.com/
#  oss-url: https://cut0820.oss-cn-hongkong.aliyuncs.com
#  bucket-name: cut0820
#
#
## 香港服务器
## 1。 mysql root 123456
## 2。 phoneparts phoneparts phoneparts