name: 思腾-生产环境
# 触发条件：v5 分支提交就触发活动。
on:
  push:
    branches: v61
# 步骤流程：
jobs:
  job_1:
    name: 构建项目
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - name: Checkout Code
        uses: actions/checkout@v2

      # 安装JDK1.8
      - name: Setup JDK8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # 配置 Maven 缓存环境
      - name: Maven Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Maven 打包
      - name: Maven Package
        run: mvn package -Dmaven.test.skip=true

      # 发布项目
      - name: Publish Package
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        env:
          WELCOME: "ssh scp ssh pipelines"
          LASTSSH: "Doing something after copying"
        with:
          host: ${{ secrets.DEVIA_PROD_SERVER_HOST }}
          port: ${{ secrets.DEVIA_PROD_SERVER_PORT }}
          user: ${{ secrets.DEVIA_PROD_SERVER_USERNAME }}
          pass: ${{ secrets.DEVIA_PROD_SERVER_PASSWORD }}

          connect_timeout: 100s
          # 停止应用 + 创建目录（可选） + 备份数据（可选）
          first_ssh: |
            pkill -f icebartech-phoneparts
            mkdir -p /data/deploy/Java/icebartech-phoneparts

            datename=$(date +%Y%m%d%H%M%S)
            mv /data/deploy/Java/icebartech-phoneparts/icebartech-phoneparts.jar /data/deploy/Java/icebartech-phoneparts/icebartech-phoneparts.jar.bak.$datename

          # 推送文件到服务器
          scp: |
            icebartech-starter/target/icebartech-phoneparts.jar => /data/deploy/Java/icebartech-phoneparts
          # 指定目录 + 运行服务 + 退出（没法自动退出）
          # last_ssh: |
          #   cd /data/deploy/Java/icebartech-phoneparts
          #   nohup java -jar icebartech-phoneparts.jar --spring.profile.active=test > logs/start.log 2>&1 &
      # 启动服务
      - name: Start Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEVIA_PROD_SERVER_HOST }}
          port: ${{ secrets.DEVIA_PROD_SERVER_PORT }}
          username: ${{ secrets.DEVIA_PROD_SERVER_USERNAME }}
          password: ${{ secrets.DEVIA_PROD_SERVER_PASSWORD }}
          script: |
            cd /data/deploy/Java/icebartech-phoneparts
            nohup java -jar icebartech-phoneparts.jar --spring.profiles.active=dev > /u01/logs/phoneparts.log 2>&1 &

