name: V4-测试环境

# 触发条件：v4 分支提交就触发活动。
on:
  push:
    branches: v4

# 步骤流程：
jobs:
  job_2:
    name: 部署项目
#    needs: job_1
    steps:
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
        SSH_PRIVATE_KEY: 123
        REMOTE_HOST: 120.78.135.29
        REMOTE_USER: root
        REMOTE_PORT: 5822
#  job_1:
#    name: 构建项目
#    runs-on: ubuntu-latest
#    steps:
#    # 使用集成的脚本拉取 v4 代码。
#    - name: checkout @v4
#      uses: actions/checkout@v2
#    # 安装JDK1.8
#    - name: Set up JDK 1.8
#      uses: actions/setup-java@v1
#      with:
#        java-version: 1.8
#    # Maven 打包
#    - name: Build with Maven
#      run: mvn package && ls icebartech-starter/target