name: V5-测试环境
# 触发条件：v5 分支提交就触发活动。
on:
  push:
    branches: v5
# 步骤流程：
jobs:
  job_1:
    name: 构建项目
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - name: Checkout Code
        uses: actions/checkout@v2

      # 安装JDK1.8
      - name: Setup JDK8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # 配置 Maven 缓存环境
      - name: Maven Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Maven 打包
      - name: Maven Package
        run: mvn package -Dmaven.test.skip=true

      # 上传文件
      - name: Upload Files
        uses: garygrossgarten/github-action-scp@release
        with:
          host: ${{ secrets.TEST_SERVER_HOST }}
          port: ${{ secrets.TEST_SERVER_PORT }}
          username: ${{ secrets.TEST_SERVER_USERNAME }}
          password: ${{ secrets.TEST_SERVER_PASSWORD }}
          local: icebartech-starter/target/icebartech-phoneparts.jar
          remote: /data/deploy/Java/icebartech-phoneparts/icebartech-phoneparts5.jar
          concurrency: 20

      # 启动服务
      - name: Start Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TEST_SERVER_HOST }}
          port: ${{ secrets.TEST_SERVER_PORT }}
          username: ${{ secrets.TEST_SERVER_USERNAME }}
          password: ${{ secrets.TEST_SERVER_PASSWORD }}
          script: |
            cd /data/deploy/Java/icebartech-phoneparts
            nohup java -jar icebartech-phoneparts.jar --spring.profile.active=test > logs/start.log 2>&1 &