name: V5-测试环境
# 触发条件：v5 分支提交就触发活动。
on:
  push:
    branches: v5
# 步骤流程：
jobs:
  job_1:
    name: 构建项目
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - name: 拉取代码
        uses: actions/checkout@v2
      # 安装JDK1.8
      - name: 配置 Java 环境
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      # 配置 Maven 缓存环境
      - name: 配置 Maven 缓存环境
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      # Maven 打包
#      - name: Maven 打包
#        run: mvn package -Dmaven.test.skip=true

      # 发布到仓库
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: icebartech-phoneparts package
          tag_name: v1.0.0
          files: |
            pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#      # 上传文件
#      - name: upload
#        uses: garygrossgarten/github-action-scp@release
#        with:
#          host: ${{ secrets.TEST_SERVER_HOST }}
#          port: ${{ secrets.TEST_SERVER_PORT }}
#          username: ${{ secrets.TEST_SERVER_USERNAME }}
#          password: ${{ secrets.TEST_SERVER_PASSWORD }}
#          local: icebartech-starter/target/icebartech-phoneparts.jar
#          remote: /data/deploy/Java/icebartech-phoneparts/icebartech-phoneparts.jar
#          concurrency: 20
#
      # 启动服务
      - name: start application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TEST_SERVER_HOST }}
          port: ${{ secrets.TEST_SERVER_PORT }}
          username: ${{ secrets.TEST_SERVER_USERNAME }}
          password: ${{ secrets.TEST_SERVER_PASSWORD }}
          script: |
            mkdir -p /data/test4
            cd /data/test4
            ls -l
